set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'seebi/tmux-colors-solarized'

run '~/.tmux/plugins/tpm/tpm'

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

bind r source-file ~/.tmux.conf \; display "Config reloaded."

# Window numbers
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# vim everything
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g history-limit 50000

# More screenish shortcuts
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Swap on C-a C-a
bind C-a last-window

# Rename window
bind a command-prompt 'rename-window %%'
set -g automatic-rename off

# Prev/next tab
bind -n M-h prev
bind -n M-l next

# Clock
set -g status-left " #S "
set -g status-right "%H:%M "

# Term title
set -g set-titles on
set -g set-titles-string 'tmux #{session_name}'

# No delay for escape key press
set -sg escape-time 0

# Panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Same directory in the new window
bind '%' split-window -h -c '#{pane_current_path}'
bind '"' split-window -v -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'

# Colours
set -g @colors-solarized 'light'
set -g status-style fg=yellow,bg=white
