
font_family      PragmataProMonoLiga-Regular
font_size 13
enable_audio_bell   no

allow_remote_control yes
listen_on unix:/tmp/kitty
enabled_layouts splits

background            #fdf6e3
foreground            #657b83
cursor                #657b83
selection_background  #fdf6e3
color0 #073642
color8 #002b36 
color1 #dc322f
color9 #cb4b16
color2 #859900
color10 #586e75
color3 #b58900
color11 #657b83
color4 #268bd2
color12 #839496
color5 #d33682
color13 #6c71c4
color6 #2aa198
color14 #93a1a1
color7 #eee8d5
color15 #fdf6e3
selection_foreground #93a1a1

# Tab bar

tab_bar_style fade
tab_fade 1
tab_title_max_length 30

tab_bar_background      #eee8d5
active_tab_foreground   #fff
active_tab_background   #268bd2
inactive_tab_foreground #fff
inactive_tab_background #999

# Keys

# map alt+n new_tab
# map alt+h previous_tab
# map alt+l next_tab

# map alt+shift+h move_tab_backward
# map alt+shift+l move_tab_forward
